users = ["GDcheerios", "BirdPigeon"]
match_name = "test match"
initial_score = [0, 0]
final_score = [100000, 200000]
initial_playcount = [0, 0]
final_playcount = [100, 200]
mode = "teams"
team_metadata = {"godtier":["GDcheerios"], "trash":["BirdPigeon"]}
level_difficulty = "normal"